export const CREATE_RECORD = "CREATE_RECORD";
export const LOAD_RECORDS_SUCCESS = "LOAD_RECORDS_SUCCESS";
export const LOAD_DEPTS_SUCCESS = "LOAD_DEPTS_SUCCESS";
export const CREATE_RECORD_SUCCESS = "CREATE_RECORD_SUCCESS";
export const UPDATE_RECORD_SUCCESS = "UPDATE_RECORD_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const DELETE_RECORD_OPTIMISTIC = "DELETE_RECORD_OPTIMISTIC";
export const SEARCH_RECORD_SUCCESS = "SEARCH_RECORD_SUCCESS";